# Generated by Django 5.2.1 on 2025-06-01 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_account_creation', models.DateField()),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Events_on_Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_creation', models.DateTimeField()),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Tentative', 'Tentative'), ('Cancelled', 'Cancelled')], max_length=9)),
                ('recurrence', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.calendar_users')),
            ],
        ),
        migrations.CreateModel(
            name='Recurring_Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurrence_type', models.CharField(choices=[('Standard_recurrence', 'Standard_recurrence'), ('Interval_patterns', 'Interval_patterns'), ('Weekday_selection', 'Weekday_selection'), ('Relative_date_patterns', 'Relative_date_patterns')], max_length=22)),
                ('recurring_time', models.JSONField()),
                ('Event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.events_on_calendar')),
            ],
        ),
    ]
