# Generated by Django 5.2.1 on 2025-06-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_events_on_calendar_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_on_calendar',
            name='event_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='events_on_calendar',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
